const STAT_KEYS   = ['movement', 'melee', 'ranged', 'defence', 'morale', 'wounds']
const STAT_LABELS = ['MOV', 'MEL', 'RNG', 'DEF', 'MOR', 'WND']

export function exportToText(name, faction, entries, totalPoints, pointLimit) {
  const lines = []
  const topLevel = entries.filter(e => !e.attachedTo)

  lines.push(`=== ${name} ===`)
  lines.push(`Faction: ${faction}  |  ${totalPoints.toLocaleString()} / ${pointLimit.toLocaleString()} pts`)
  lines.push('')

  for (const entry of topLevel) {
    const u   = entry.unit
    const pts = u.points ? `${u.points} pts` : 'TBC'
    lines.push(`[${u.name}]  —  ${pts}`)

    const stats = entry.effectiveStats ?? u.stats ?? {}
    const statsLine = STAT_KEYS.map((k, i) => `${STAT_LABELS[i]} ${stats[k] ?? '—'}`).join('  ')
    lines.push(`  Stats: ${statsLine}`)

    if (u.weapons?.length) {
      lines.push(`  Weapons:`)
      for (const w of u.weapons) {
        lines.push(`    ${w.name}  Range ${w.range ?? '—'}  Atk ${w.attacks ?? '—'}  Dmg ${w.damage ?? '—'}  AP ${w.armourPiercing ?? '—'}`)
      }
    }

    if (u.specialRules?.length) {
      lines.push(`  Special Rules: ${u.specialRules.join(', ')}`)
    }

    const attachments = (entry.attachments ?? [])
      .map(id => entries.find(e => e.instanceId === id))
      .filter(Boolean)

    for (const a of attachments) {
      const aPts  = a.unit.points ? `${a.unit.points} pts` : 'TBC'
      const aType = a.unit.attachable?.asAttachment?.attachmentType ?? 'attachment'
      lines.push(`  └─ ${a.unit.name}  (${aType})  —  ${aPts}`)
      const buffs = (entry.buffSources ?? [])
        .filter(b => b.fromUnit === a.unit.name && b.stat)
        .map(b => `${b.stat.toUpperCase()} ${b.delta > 0 ? '+' : ''}${b.delta}`)
      if (buffs.length) lines.push(`     Grants: ${buffs.join(', ')}`)
    }

    lines.push('')
  }

  lines.push('---')
  lines.push(`Generated by CFB Army Builder — ${new Date().toLocaleDateString()}`)
  return lines.join('\n')
}

export function downloadTxt(name, faction, entries, totalPoints, pointLimit) {
  const text = exportToText(name, faction, entries, totalPoints, pointLimit)
  const blob = new Blob([text], { type: 'text/plain' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `${name.replace(/\s+/g, '_')}.txt`
  a.click()
  URL.revokeObjectURL(url)
}
